# Generated by Django 2.1.4 on 2018-12-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181226_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='profile_pictures'),
        ),
    ]
