# Generated by Django 2.1.4 on 2018-12-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181226_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
