# Generated by Django 2.1.4 on 2018-12-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181226_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
